"""profile table

Revision ID: 6e1f1f0e772e
Revises: de1c638b12ff
Create Date: 2025-11-16 02:02:23.513021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1f1f0e772e'
down_revision: Union[str, None] = 'de1c638b12ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('state_of_residence', sa.String(), nullable=True),
    sa.Column('state_tax_authority', sa.String(), nullable=True),
    sa.Column('NIN', sa.String(), nullable=True),
    sa.Column('employment_income', sa.Float(), nullable=True),
    sa.Column('business_income', sa.Float(), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=True),
    sa.Column('chargeable_gains', sa.Float(), nullable=True),
    sa.Column('pension_contribution', sa.Float(), nullable=True),
    sa.Column('voluntary_pension_contribution', sa.Float(), nullable=True),
    sa.Column('national_housing_fund', sa.Float(), nullable=True),
    sa.Column('National_health_insurance_scheme', sa.Float(), nullable=True),
    sa.Column('life_insurance_premium', sa.Float(), nullable=True),
    sa.Column('house_rent', sa.Float(), nullable=True),
    sa.Column('mortgage_interest', sa.Float(), nullable=True),
    sa.Column('losses_allowed', sa.Float(), nullable=True),
    sa.Column('capital_allowances', sa.Float(), nullable=True),
    sa.Column('estimated_tax', sa.Float(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name=op.f('fk_user_profile_email_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_user_profile'))
    )
    op.create_index(op.f('ix_user_profile_email'), 'user_profile', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_email'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
