"""employment_type

Revision ID: ddcd34bb613f
Revises: feadbe94650d
Create Date: 2025-12-13 12:07:26.637294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcd34bb613f'
down_revision: Union[str, None] = 'feadbe94650d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('employment_type', sa.String(), nullable=True))
    op.drop_column('user_profile', 'occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('occupation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'employment_type')
    # ### end Alembic commands ###
